import type { Metadata } from "next";
import { Jost } from "next/font/google";
import "./globals.css";
import "aos/dist/aos.css";
import { AOS } from "aos";
const inter = Jost({
  preload: false,
});

export const metadata: Metadata = {
  title: "Edu CMC",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
